version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq
      - wget http://www-eu.apache.org/dist/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz
      - tar xzf apache-maven-3.8.1-bin.tar.gz
      - ln -s apache-maven-3.8.1 maven
  build:
    commands:
      - mvn test    
